### ISSUE TITLE
isArray should support readonly arrays

### ISSUE THREAD

**Issue by wmaurer** [justinlettau/ts-util-is#43]
## Describe the Feature

isArray should support readonly arrays

## Suggested Solution

Change type signature to:
```isArray(value: any): value is any[] | readonly any[]```

## Other Information

PR coming.

**Comment by justinlettau** [comment]
@wmaurer This should be resolved in [v2.0.2](https://github.com/justinlettau/ts-util-is/blob/master/CHANGELOG.md#202-2021-12-04). Let me know if you still have issues. Thanks!
